export default {
    ADD_MUSIC_TRACKS:'ADD_MUSIC_TRACKS',
    SET_CURRENT_TRACK:'SET_CURRENT_TRACK',
    SET_CURRENT_ARTWORK:'SET_CURRENT_ARTWORK',
    ADD_SORTED_TRACKS:'ADD_SORTED_TRACKS',
    UPDATE_SORTED_TRACKS:'UPDATE_SORTED_TRACKS',
    ADD_SORTED_fILTER_ITEM:'ADD_SORTED_fILTER_ITEM',
    UPDATE_SORTED_fILTER_ITEM:'UPDATE_SORTED_fILTER_ITEM'
}